import express from "express";
import cors from "cors";
import { healthRouter } from "./modules/health/health.routes.js";
import { authRouter, meHandler } from "./modules/auth/auth.routes.js";
import { requireAuth } from "./modules/auth/auth.middleware.js";
import { requestContextMiddleware } from "./common/request-context.js";
import { traceContextMiddleware } from "./common/trace-context.js";
import { requestLoggerMiddleware } from "./common/request-logger.js";
import { rateLimitMiddleware } from "./common/rate-limit-middleware.js";
import { idempotencyMiddleware } from "./common/idempotency-middleware.js";
import { metricsMiddleware } from "./common/metrics.js";
import { securityHeadersMiddleware } from "./common/security-headers-middleware.js";
import { errorMiddleware } from "./common/error-middleware.js";
import { requireRoles } from "./modules/auth/rbac.middleware.js";
import { coursesRouter } from "./modules/courses/courses.routes.js";
import { learnerStateRouter } from "./modules/learner-state/learner-state.routes.js";
import { consentRouter } from "./modules/consent/consent.routes.js";
import { conversationsRouter } from "./modules/conversations/conversations.routes.js";
import { turnsRouter } from "./modules/conversations/turns.routes.js";
import { policiesRouter } from "./modules/policies/policies.routes.js";
import { reviewsRouter } from "./modules/reviews/reviews.routes.js";
import { adminRouter } from "./modules/admin/admin.routes.js";
import { auditRouter } from "./modules/audit/audit.routes.js";
import { usersRouter } from "./modules/users/users.routes.js";

export const app = express();

app.disable("x-powered-by");
app.use(cors());
app.use(express.json());
app.use(securityHeadersMiddleware);
app.use(requestContextMiddleware);
app.use(traceContextMiddleware);
app.use(requestLoggerMiddleware);
app.use(metricsMiddleware);
app.use(rateLimitMiddleware);

app.use("/api/v1", healthRouter);
app.use("/api/v1/auth", authRouter);
app.get("/api/v1/auth/me", requireAuth, meHandler);
app.use("/api/v1/users", requireAuth, requireRoles(["student", "faculty", "advisor", "admin", "auditor"]), idempotencyMiddleware, usersRouter);
app.use("/api/v1/courses", requireAuth, requireRoles(["student", "faculty", "advisor", "admin", "auditor"]), coursesRouter);
app.use("/api/v1/learners", requireAuth, requireRoles(["student", "faculty", "advisor", "admin", "auditor"]), idempotencyMiddleware, learnerStateRouter);
app.use("/api/v1/consents", requireAuth, requireRoles(["student", "faculty", "advisor", "admin", "auditor"]), idempotencyMiddleware, consentRouter);
app.use("/api/v1/conversations", requireAuth, requireRoles(["student", "faculty", "advisor", "admin", "auditor"]), idempotencyMiddleware, conversationsRouter);
app.use("/api/v1/turns", requireAuth, requireRoles(["student", "faculty", "advisor", "admin", "auditor"]), turnsRouter);
app.use("/api/v1/policies", requireAuth, requireRoles(["faculty", "admin"]), idempotencyMiddleware, policiesRouter);
app.use("/api/v1/reviews", requireAuth, requireRoles(["faculty", "admin"]), idempotencyMiddleware, reviewsRouter);
app.use("/api/v1/admin", requireAuth, requireRoles(["admin"]), idempotencyMiddleware, adminRouter);
app.use("/api/v1/audit", requireAuth, requireRoles(["admin", "auditor"]), auditRouter);

app.use(errorMiddleware);
